name: Release

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@v8.2.0
        name: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          call: release --gh-user ${{ github.actor }} --gh-auth-token env://GH_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
